

#main : main.cpp
#	mpic++ main.cpp -o main -I/usr/include/eigen3


# DAINT 
main : main.cpp
	CC main.cpp -o main -I/users/lgaedkem/applications/eigen

main_dummy_ex : main_dummy_ex.cpp
	CC $< -o $@ 
