
eigen_pardiso: eigen_pardiso.cpp
	g++ -I /home/x_gaedkelb/applications/eigen-3.3.9 -DEIGEN_USE_MKL_ALL -DMKL_LP64 -I${MKLROOT}/include eigen_pardiso.cpp -o eigen_pardiso -L${MKLROOT}/lib/intel64 -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl

