# makefile


test: test.cpp
	g++ -I /home/x_gaedkelb/applications/eigen-3.3.9 test.cpp -o test

build_precond: build_precond.cpp
	g++ -I /home/x_gaedkelb/applications/eigen-3.3.9 build_precond.cpp -o build_precond
